# syntax=docker/dockerfile:1

ARG BASE_IMAGE=ubuntu:24.04

FROM quay.io/kairos/kairos-init:v0.6.2 AS kairos-init

FROM ${BASE_IMAGE} AS base-kairos
ARG VERSION
RUN --mount=type=bind,from=kairos-init,src=/kairos-init,dst=/kairos-init /kairos-init --level debug --version "${VERSION}"

RUN --mount=type=secret,id=ubuntu-pro-token pro attach "$(cat /run/secrets/ubuntu-pro-token)"
RUN pro status
RUN pro enable usg
RUN apt install usg
RUN usg fix cis_level1_server
RUN apt install -y rsync
