# syntax=docker/dockerfile:1

ARG BASE_IMAGE_VERSION
ARG BASE_IMAGE_REGISTRY
ARG BASE_IMAGE="${BASE_IMAGE_REGISTRY}/base-image:${BASE_IMAGE_VERSION}"

FROM ${BASE_IMAGE}
ARG VERSION=0.0.0-dev.0

RUN --mount=type=secret,id=ubuntu-pro-token pro attach "$(cat /run/secrets/ubuntu-pro-token)"
RUN pro status
RUN pro enable usg
RUN apt install usg
RUN usg fix cis_level1_server
RUN apt install -y rsync
