# syntax=docker/dockerfile:1

ARG K8S_VERSION=v1.36.4
ARG GO_VERSION=1.25.10
ARG RELEASE_VERSION=v0.21.0

FROM golang:${GO_VERSION} AS build
ARG K8S_VERSION
ARG TARGETARCH
ARG RELEASE_VERSION
ENV GOFIPS140=certified CGO_ENABLED=0
RUN apt-get update && apt-get install -y --no-install-recommends git rsync make && rm -rf /var/lib/apt/lists/*
WORKDIR /src
RUN git clone --depth 1 --branch "${K8S_VERSION}" https://github.com/kubernetes/kubernetes.git
WORKDIR /src/kubernetes
RUN make kubeadm kubelet kubectl KUBE_BUILD_PLATFORMS="linux/${TARGETARCH}"
RUN mkdir -p /out/usr/bin /out/usr/lib/systemd/system/kubelet.service.d && \
    cp _output/local/go/bin/linux_${TARGETARCH}/kubeadm /out/usr/bin/ 2>/dev/null || cp _output/bin/kubeadm /out/usr/bin/ && \
    cp _output/local/go/bin/linux_${TARGETARCH}/kubelet /out/usr/bin/ 2>/dev/null || cp _output/bin/kubelet /out/usr/bin/ && \
    cp _output/local/go/bin/linux_${TARGETARCH}/kubectl /out/usr/bin/ 2>/dev/null || cp _output/bin/kubectl /out/usr/bin/
RUN curl -fsSL "https://raw.githubusercontent.com/kubernetes/release/${RELEASE_VERSION}/cmd/krel/templates/latest/kubelet/kubelet.service" \
      > /out/usr/lib/systemd/system/kubelet.service && \
    curl -fsSL "https://raw.githubusercontent.com/kubernetes/release/${RELEASE_VERSION}/cmd/krel/templates/latest/kubeadm/10-kubeadm.conf" \
      > /out/usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf
RUN mkdir -p /out/etc/systemd/system/multi-user.target.wants && \
    ln -sf /usr/lib/systemd/system/kubelet.service /out/etc/systemd/system/multi-user.target.wants/kubelet.service

FROM scratch
COPY --from=build /out /
