# syntax=docker/dockerfile:1
# Dynamically linked containerd against the target OS glibc, plus runc + CNI.
# BASE_IMAGE is the distro (ubuntu:24.04, rockylinux:9), not the Kairos image.

ARG BASE_IMAGE
ARG GO_VERSION

FROM golang:${GO_VERSION} AS gobuild
FROM ${BASE_IMAGE} AS build
ARG CONTAINERD_VERSION
ARG RUNC_VERSION
ARG CNI_PLUGINS_VERSION
ARG TARGETARCH
COPY --from=gobuild /usr/local/go /usr/local/go
ENV PATH=/usr/local/go/bin:$PATH GOFIPS140=certified GOTOOLCHAIN=local CGO_ENABLED=1
RUN if command -v apt-get >/dev/null; then \
      apt-get update && apt-get install -y --no-install-recommends git make gcc libc6-dev libseccomp-dev pkg-config curl ca-certificates; \
    else \
      dnf -y install git make gcc libseccomp-devel pkgconfig curl ca-certificates; \
    fi

WORKDIR /src
RUN git clone --depth 1 --branch "v${CONTAINERD_VERSION}" https://github.com/containerd/containerd.git
WORKDIR /src/containerd
RUN make bin/containerd bin/containerd-shim-runc-v2 bin/ctr

WORKDIR /src
RUN git clone --depth 1 --branch "v${RUNC_VERSION}" https://github.com/opencontainers/runc.git
WORKDIR /src/runc
RUN CGO_ENABLED=1 make bin/runc

WORKDIR /src
RUN git clone --depth 1 --branch "v${CNI_PLUGINS_VERSION}" https://github.com/containernetworking/plugins.git
WORKDIR /src/plugins
RUN CGO_ENABLED=0 ./build_linux.sh

FROM ${BASE_IMAGE}
COPY --from=build /src/containerd/bin/containerd /usr/bin/containerd
COPY --from=build /src/containerd/bin/containerd-shim-runc-v2 /usr/bin/containerd-shim-runc-v2
COPY --from=build /src/containerd/bin/ctr /usr/bin/ctr
COPY --from=build /src/runc/bin/runc /usr/bin/runc
COPY --from=build /src/plugins/bin /opt/cni/bin
COPY sysexts/containerd.service /usr/lib/systemd/system/containerd.service
RUN mkdir -p /etc/systemd/system/multi-user.target.wants && \
    ln -sf /usr/lib/systemd/system/containerd.service /etc/systemd/system/multi-user.target.wants/containerd.service
