# syntax=docker/dockerfile:1

ARG GO_VERSION

FROM golang:${GO_VERSION} AS build
ARG K8S_VERSION
ARG TARGETARCH
ARG RELEASE_VERSION
ARG PAUSE_TAG
ENV GOFIPS140=certified CGO_ENABLED=0
RUN apt-get update && apt-get install -y --no-install-recommends git rsync make && rm -rf /var/lib/apt/lists/*
WORKDIR /src
COPY scripts/enable-fips-go.sh /tmp/enable-fips-go.sh
RUN git clone --depth 1 --branch "${K8S_VERSION}" https://github.com/kubernetes/kubernetes.git
WORKDIR /src/kubernetes
RUN eval "$(bash /tmp/enable-fips-go.sh /src/kubernetes/.go-version)" \
 && make kubeadm kubelet kubectl KUBE_BUILD_PLATFORMS="linux/${TARGETARCH}"
RUN mkdir -p /out/usr/bin /out/usr/lib/systemd/system/kubelet.service.d /out/usr/lib/kairos && \
    cp "_output/local/bin/linux/${TARGETARCH}/kubeadm" /out/usr/bin/ && \
    cp "_output/local/bin/linux/${TARGETARCH}/kubelet" /out/usr/bin/ && \
    cp "_output/local/bin/linux/${TARGETARCH}/kubectl" /out/usr/bin/ && \
    printf '%s\n' "${PAUSE_TAG}" >/out/usr/lib/kairos/pause-tag
RUN curl -fsSL "https://raw.githubusercontent.com/kubernetes/release/${RELEASE_VERSION}/cmd/krel/templates/latest/kubelet/kubelet.service" \
      > /out/usr/lib/systemd/system/kubelet.service && \
    curl -fsSL "https://raw.githubusercontent.com/kubernetes/release/${RELEASE_VERSION}/cmd/krel/templates/latest/kubeadm/10-kubeadm.conf" \
      > /out/usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf
RUN mkdir -p /out/etc/systemd/system/multi-user.target.wants && \
    ln -sf /usr/lib/systemd/system/kubelet.service /out/etc/systemd/system/multi-user.target.wants/kubelet.service

FROM scratch
COPY --from=build /out /
